reads:
    alligator-mississippiensis: ../tests/test-data/raw-reads/alligator-mississippiensis/
    gallus-gallus: ../tests/test-data/raw-reads/gallus-gallus
    peromyscus-maniculatus: ../tests/test-data/raw-reads/peromyscus-maniculatus
    rana-sphenocephafa: ../tests/test-data/raw-reads/rana-sphenocephafa

contigs:
    alligator-mississippiensis: ../tests/test-data/contigs/alligator_mississippiensis.contigs.fasta
    gallus-gallus: ../tests/test-data/contigs/gallus_gallus.contigs.fasta
    peromyscus-maniculatus: ../tests/test-data/contigs/peromyscus_maniculatus.contigs.fasta
    rana-sphenocephafa: ../tests/test-data/contigs/rana_sphenocephafa.contigs.fasta